
#include "form/rv32a.h"

#include "form/generic.h"
#include "parse.h"

const struct formation_t rv32a[] = {
	{ "lr.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x08 } },
	{ "lr.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0B } },
	{ "lr.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0A } },
	{ "lr.w.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0B } },
	{ "sc.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0C } },
	{ "sc.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0D } },
	{ "sc.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0F } },
	{ "sc.w.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x0F } },

	{ "amoswap.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x04 } },
	{ "amoswap.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x05 } },
	{ "amoswap.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x06 } },
	{ "amoswap.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x07 } },
	{ "amoadd.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x00 } },
	{ "amoadd.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x01 } },
	{ "amoadd.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x02 } },
	{ "amoadd.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x03 } },
	{ "amoxor.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x10 } },
	{ "amoxor.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x12 } },
	{ "amoxor.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x11 } },
	{ "amoxor.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x13 } },
	{ "amoor.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x20 } },
	{ "amoor.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x21 } },
	{ "amoor.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x22 } },
	{ "amoor.w.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x23 } },
	{ "amoand.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x30 } },
	{ "amoand.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x31 } },
	{ "amoand.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x32 } },
	{ "amoand.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x33 } },
	{ "amomin.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x40 } },
	{ "amomin.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x41 } },
	{ "amomin.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x42 } },
	{ "amomin.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x43 } },
	{ "amomax.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x50 } },
	{ "amomax.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x51 } },
	{ "amomax.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x52 } },
	{ "amomax.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x53 } },
	{ "amominu.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x60 } },
	{ "amominu.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x61 } },
	{ "amominu.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x62 } },
	{ "amominu.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x63 } },
	{ "amomaxu.w", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x70 } },
	{ "amomaxu.w.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x71 } },
	{ "amomaxu.w.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x2, 0x72 } },
	{ "amomaxu.w.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x2, 0x73 } },

	END_FORMATION
};
