
#include "form/rv64a.h"

#include "form/generic.h"
#include "parse.h"

const struct formation_t rv64a[] = {
	{ "lr.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x08 } },
	{ "lr.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0B } },
	{ "lr.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0A } },
	{ "lr.d.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0B } },
	{ "sc.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0C } },
	{ "sc.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0D } },
	{ "sc.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0F } },
	{ "sc.d.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x0F } },

	{ "amoswap.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x04 } },
	{ "amoswap.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x05 } },
	{ "amoswap.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x06 } },
	{ "amoswap.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x07 } },
	{ "amoadd.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x00 } },
	{ "amoadd.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x01 } },
	{ "amoadd.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x02 } },
	{ "amoadd.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x03 } },
	{ "amoxor.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x10 } },
	{ "amoxor.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x12 } },
	{ "amoxor.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x11 } },
	{ "amoxor.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x13 } },
	{ "amoor.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x20 } },
	{ "amoor.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x21 } },
	{ "amoor.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x22 } },
	{ "amoor.d.aq.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x23 } },
	{ "amoand.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x30 } },
	{ "amoand.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x31 } },
	{ "amoand.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x32 } },
	{ "amoand.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x33 } },
	{ "amomin.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x40 } },
	{ "amomin.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x41 } },
	{ "amomin.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x42 } },
	{ "amomin.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x43 } },
	{ "amomax.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x50 } },
	{ "amomax.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x51 } },
	{ "amomax.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x52 } },
	{ "amomax.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x53 } },
	{ "amominu.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x60 } },
	{ "amominu.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x61 } },
	{ "amominu.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x62 } },
	{ "amominu.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x63 } },
	{ "amomaxu.d", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x70 } },
	{ "amomaxu.d.rl", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x71 } },
	{ "amomaxu.d.aq", &form_rtype, &parse_rtype, { 4, OP_AMO, 0x3, 0x72 } },
	{ "amomaxu.d.aq.rl",
	  &form_rtype,
	  &parse_rtype,
	  { 4, OP_AMO, 0x3, 0x73 } },

	END_FORMATION
};
