name: Compiler Environment Setup
description: Setup environment variables for a compiler

inputs:
  compiler:
    description: "The compiler name (i.e. clang, gcc or msvc)"
    required: true
    default: clang

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: pip install meson ninja
      shell: bash

    - run: brew install llvm
      if: ${{ runner.os == 'macOS' }}
      shell: bash

    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.compiler == 'msvc' }}

    - run: echo "CC=$(which ${{ matrix.compiler }})" >> $GITHUB_ENV
      if: ${{ matrix.compiler != 'msvc' }}
      shell: bash

    - run: echo "CC_LD=lld" >> $GITHUB_ENV
      if: ${{ matrix.compiler == 'clang' }}
      shell: bash

