name: build

on:
  push:
    branches: [ "master" ]
    paths:
      - '*/**'
      - '**/meson.build'
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        compiler: [ gcc, clang ]
        include:
          - os: windows-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/setup_cc_env
      with: 
        compiler: ${{ matrix.compiler }}

    - run: meson setup build

    - run: meson compile -C build

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ matrix.os }}-${{ matrix.compiler }}
        path: build/meson-logs/
        retention-days: 5

