name: coverage

on:
  push:
    branches: [ "master" ]
    paths:
      - '*/**'
      - '**/meson.build'
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Coverage
      uses: BSFishy/meson-build@v1
      with:
        action: coverage

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ matrix.os }}
        path: build/meson-logs/
        retention-days: 5

