name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Argp-Standalone (MAC)
      if: runner.os == 'macOS'
      run: brew install argp-standalone
    - name: ldir
      if: runner.os == 'macOS'
      run: |
          ls /usr/lib
          ls /usr/lib/*
          ls /usr/local/opt/argp-standalone
          ls /usr/local/opt/argp-standalone/*
          find /usr -name libargp-standalone.a


    - name: Compile
      run: make

    - name: Test
      run: make test
