name: Meson CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: sudo apt-get install llvm
      if: matrix.os == 'ubuntu-latest'
    - run: brew install llvm
      if: matrix.os == 'macos-latest'
    - run: choco install llvm unxutils
      if: matrix.os == 'windows-latest'

    - run: pip install meson ninja

    - name: Configure
      run: meson setup build

    - name: Build
      run: meson compile -C build

    - run: ls -a . *
      if: matrix.os != 'windows-latest'

    - name: Test
      run: meson test -C build

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: meson-logs
        path: build/meson-logs/
        retention-days: 5

