name: Meson CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Ubuntu LLVM
      run: sudo apt-get install llvm
      if: matrix.os == 'ubuntu-latest'
    - name: MacOS LLVM
      run: |
        brew install llvm
        echo 'PATH="/usr/local/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
      if: matrix.os == 'macos-latest'

    - name: Install Meson
      run: pip install meson ninja

    - name: Version Info
      run: |
        ls /usr/local/opt/llvm/bin/clang
        ls /usr/bin
        meson --version
        ninja --version
        /usr/local/opt/llvm/bin/clang --version

    - name: Configure
      run: meson setup build

    - name: Build
      run: meson compile -C build

    - name: Test
      run: meson test -C build

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs-${{ matrix.os }}
        path: build/meson-logs/
        retention-days: 5

